spring.application.name=ms-bff

# Puerto del servidor BFF
server.port=8085

# URLs de microservicios
ms.auth.url=http://localhost:8080
ms.weather.url=http://localhost:8081
ms.sync.url=http://localhost:8083

# CONFIGURACIÓN CORS
spring.web.cors.allowed-origins=http://localhost:8084,http://localhost:19000,http://localhost:19006,http://localhost:3000,http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
